USE [master]
GO

/****** Object:  Database [SampleDB]    Script Date: 08/04/2019 00:08:48 ******/
CREATE DATABASE [SampleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleDB', FILENAME = N'C:\Users\manpc\SampleDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleDB_log', FILENAME = N'C:\Users\manpc\SampleDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SampleDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
    EXEC [SampleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SampleDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SampleDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SampleDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SampleDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SampleDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SampleDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SampleDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SampleDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SampleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SampleDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SampleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SampleDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SampleDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SampleDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SampleDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SampleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SampleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SampleDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SampleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SampleDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SampleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SampleDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SampleDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SampleDB] SET  MULTI_USER 
GO

ALTER DATABASE [SampleDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SampleDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SampleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SampleDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SampleDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SampleDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SampleDB] SET  READ_WRITE 
GO


USE [SampleDB]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 08/04/2019 01:13:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products]
(
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [GroupCode] [int] NULL,
    [CreatedOn] [varchar](19) NULL,
    [DeletedOn] [varchar](19) NULL,
    [Material] [varchar](50) NULL,
    [Weight] [varchar](50) NULL,
    [Shape] [varchar](50) NULL,
    [Appearance] [varchar](19) NULL,
    [Examination] [varchar](50) NULL,
    [Volume] [int] NULL,
    [Value] [int] NULL,
    [Quantity] [int] NULL,
    [NumParts] [varchar](50) NULL,
    [NumOperations] [varchar](19) NULL,
    [Protection] [varchar](50) NULL,
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
